var SLACK_BOT_TOKEN = process.env.SLACK_BOT_TOKEN;
var SLACK_CHANNEL_ID = process.env.SLACK_CHANNEL_ID;
var YAML_FOLDER_LOCATION = process.env.YAML_FOLDER_LOCATION;


module.exports.SLACK_BOT_TOKEN = SLACK_BOT_TOKEN;
module.exports.YAML_FOLDER_LOCATION = YAML_FOLDER_LOCATION;
module.exports.SLACK_CHANNEL_ID = SLACK_CHANNEL_ID;
